#!/bin/bash

# https://github.com/5412x/m0td

echo -e "Last login: `last --ip $USER | head -1 | cut -c 20- | cut -c -38`\c"  | lolcat && cat /etc/timezone | lolcat
hostname -i | figlet | lolcat
pfetch | lolcat
